
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT FMT FTM FUNC ID IMPORT LBRACE LPAREN MAIN PACKAGE PRINTLN RBRACE RPAREN SEMICOLON STRINGprogram : package_decl import_decl func_declpackage_decl : PACKAGE MAINimport_decl : IMPORT STRINGfunc_decl : FUNC MAIN LPAREN RPAREN LBRACE stmt RBRACEstmt : FMT DOT PRINTLN LPAREN STRING RPAREN'
    
_lr_action_items = {'PACKAGE':([0,],[3,]),'$end':([1,7,16,],[0,-1,-4,]),'IMPORT':([2,6,],[5,-2,]),'MAIN':([3,8,],[6,10,]),'FUNC':([4,9,],[8,-3,]),'STRING':([5,19,],[9,20,]),'LPAREN':([10,18,],[11,19,]),'RPAREN':([11,20,],[12,21,]),'LBRACE':([12,],[13,]),'FMT':([13,],[15,]),'RBRACE':([14,21,],[16,-5,]),'DOT':([15,],[17,]),'PRINTLN':([17,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'package_decl':([0,],[2,]),'import_decl':([2,],[4,]),'func_decl':([4,],[7,]),'stmt':([13,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> package_decl import_decl func_decl','program',3,'p_program','app.py',110),
  ('package_decl -> PACKAGE MAIN','package_decl',2,'p_package_decl','app.py',113),
  ('import_decl -> IMPORT STRING','import_decl',2,'p_import_decl','app.py',116),
  ('func_decl -> FUNC MAIN LPAREN RPAREN LBRACE stmt RBRACE','func_decl',7,'p_func_decl','app.py',119),
  ('stmt -> FMT DOT PRINTLN LPAREN STRING RPAREN','stmt',6,'p_stmt','app.py',122),
]
